import { Schema, model, Model } from "mongoose";
import { IRole } from "../types";

const rolePermissionSchema = new Schema(
  {
    doctype: { type: String, required: true },
    read: { type: Boolean, default: false },
    write: { type: Boolean, default: false },
    create: { type: Boolean, default: false },
    delete: { type: Boolean, default: false },
    submit: { type: Boolean, default: false },
    cancel: { type: Boolean, default: false },
    amend: { type: Boolean, default: false },
  },
  { _id: false },
);

const roleSchema = new Schema<IRole>(
  {
    name: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    description: {
      type: String,
      default: "",
    },
    isSystemRole: {
      type: Boolean,
      default: false,
    },
    permissions: {
      type: [rolePermissionSchema],
      default: [],
    },
  },
  { timestamps: true },
);

const Role: Model<IRole> = model<IRole>("Role", roleSchema);

/**
 * Seed default system roles.
 * Called once during initial setup.
 */
export async function seedDefaultRoles(): Promise<void> {
  const defaultRoles = [
    {
      name: "System Manager",
      description: "Full system access — all permissions on all doctypes",
      isSystemRole: true,
      permissions: [], // System Manager bypasses permission checks
    },
    {
      name: "Accounts Manager",
      description: "Full access to accounting module",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Journal Entry",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Payment Entry",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Sales Invoice",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Purchase Invoice",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Account",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: false,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Company",
          read: true,
          write: true,
          create: false,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Accounts User",
      description: "Basic access to accounting — create and read",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Journal Entry",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Payment Entry",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Sales Invoice",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Purchase Invoice",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Account",
          read: true,
          write: false,
          create: false,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Stock Manager",
      description: "Full access to stock/inventory module",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Stock Entry",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Delivery Note",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Purchase Receipt",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Item",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: false,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Warehouse",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Stock User",
      description: "Basic access to stock/inventory",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Stock Entry",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Item",
          read: true,
          write: false,
          create: false,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Warehouse",
          read: true,
          write: false,
          create: false,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Sales Manager",
      description: "Full access to selling module",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Quotation",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Sales Order",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Sales Invoice",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Customer",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Sales User",
      description: "Basic access to selling",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Quotation",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Sales Order",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Customer",
          read: true,
          write: false,
          create: true,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Purchase Manager",
      description: "Full access to buying module",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Purchase Order",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Purchase Invoice",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Supplier",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Purchase User",
      description: "Basic access to buying",
      isSystemRole: true,
      permissions: [
        {
          doctype: "Purchase Order",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Supplier",
          read: true,
          write: false,
          create: true,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
      ],
    },
    {
      name: "Manufacturing Manager",
      description: "Full access to manufacturing",
      isSystemRole: true,
      permissions: [
        {
          doctype: "BOM",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Work Order",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
        {
          doctype: "Job Card",
          read: true,
          write: true,
          create: true,
          delete: true,
          submit: true,
          cancel: true,
          amend: true,
        },
      ],
    },
    {
      name: "Manufacturing User",
      description: "Basic access to manufacturing",
      isSystemRole: true,
      permissions: [
        {
          doctype: "BOM",
          read: true,
          write: false,
          create: false,
          delete: false,
          submit: false,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Work Order",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
        {
          doctype: "Job Card",
          read: true,
          write: true,
          create: true,
          delete: false,
          submit: true,
          cancel: false,
          amend: false,
        },
      ],
    },
  ];

  for (const role of defaultRoles) {
    await Role.findOneAndUpdate(
      { name: role.name },
      { $setOnInsert: role },
      { upsert: true, new: true },
    );
  }

  console.log("Default roles seeded");
}

export default Role;
