import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import organizationRoutes from "./organization.routes";
import roleRoutes from "./role.routes";
import accountRoutes from "./account.routes";
import contactRoutes from "./contact.routes";
import itemRoutes from "./item.routes";
import currencyRoutes from "./currency.routes";
import settingsRoutes from "./settings.routes";
import quoteRoutes from "./quote.routes";
import salesOrderRoutes from "./sales-order.routes";
import invoiceRoutes from "./invoice.routes";
import recurringInvoiceRoutes from "./recurring-invoice.routes";
import deliveryChallanRoutes from "./delivery-challan.routes";
import uploadRoutes from "./upload.routes";
import gstinRoutes from "./gstin.routes";
import expenseRoutes from "./expense.routes";
import recurringExpenseRoutes from "./recurring-expense.routes";
import projectRoutes from "./projects";
import currencyAdjustmentRoutes from "./currency-adjustment.routes";
import bulkUpdateRoutes from "./bulk-update.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/organizations", organizationRoutes);
router.use("/roles", roleRoutes);
router.use("/accounts", accountRoutes);
router.use("/contacts", contactRoutes);
router.use("/items", itemRoutes);
router.use("/currencies", currencyRoutes);
router.use("/settings", settingsRoutes);
router.use("/quotes", quoteRoutes);
router.use("/sales-orders", salesOrderRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/recurring-invoices", recurringInvoiceRoutes);
router.use("/delivery-challans", deliveryChallanRoutes);
router.use("/upload", uploadRoutes);
router.use("/gstin", gstinRoutes);
router.use("/expenses", expenseRoutes);
router.use("/recurring-expenses", recurringExpenseRoutes);
router.use("/projects", projectRoutes);
router.use("/currency-adjustments", currencyAdjustmentRoutes);
router.use("/bulk-update", bulkUpdateRoutes);

export default router;
