import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import organizationRoutes from "./organization.routes";
import roleRoutes from "./role.routes";
import accountRoutes from "./account.routes";
import contactRoutes from "./contact.routes";
import itemRoutes from "./item.routes";
import currencyRoutes from "./currency.routes";
import settingsRoutes from "./settings.routes";
import salesOrderRoutes from "./sales-order.routes";
import invoiceRoutes from "./invoice.routes";
import uploadRoutes from "./upload.routes";
import gstinRoutes from "./gstin.routes";
import expenseRoutes from "./expense.routes";
import recurringExpenseRoutes from "./recurring-expense.routes";
import tdsTaxRoutes from "./tds-tax.routes";
import tcsTaxRoutes from "./tcs-tax.routes";
import purchaseOrderRoutes from "./purchase-order.routes";
import billRoutes from "./bill.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/organizations", organizationRoutes);
router.use("/roles", roleRoutes);
router.use("/accounts", accountRoutes);
router.use("/contacts", contactRoutes);
router.use("/items", itemRoutes);
router.use("/currencies", currencyRoutes);
router.use("/settings", settingsRoutes);
router.use("/sales-orders", salesOrderRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/upload", uploadRoutes);
router.use("/gstin", gstinRoutes);
router.use("/expenses", expenseRoutes);
router.use("/recurring-expenses", recurringExpenseRoutes);
router.use("/tds-taxes", tdsTaxRoutes);
router.use("/tcs-taxes", tcsTaxRoutes);
router.use("/purchase-orders", purchaseOrderRoutes);
router.use("/bills", billRoutes);

export default router;
