import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import organizationRoutes from "./organization.routes";
import roleRoutes from "./role.routes";
import accountRoutes from "./account.routes";
import contactRoutes from "./contact.routes";
import itemRoutes from "./item.routes";
import currencyRoutes from "./currency.routes";
import settingsRoutes from "./settings.routes";
import quoteRoutes from "./quote.routes";
import salesOrderRoutes from "./sales-order.routes";
import invoiceRoutes from "./invoice.routes";
import creditNoteRoutes from "./credit-note.routes";
import recurringInvoiceRoutes from "./recurring-invoice.routes";
import deliveryChallanRoutes from "./delivery-challan.routes";
import uploadRoutes from "./upload.routes";
import gstinRoutes from "./gstin.routes";
import expenseRoutes from "./expense.routes";
import recurringExpenseRoutes from "./recurring-expense.routes";
import recurringBillRoutes from "./recurring-bill.routes";
import tdsTaxRoutes from "./tds-tax.routes";
import tcsTaxRoutes from "./tcs-tax.routes";
import purchaseOrderRoutes from "./purchase-order.routes";
import purchaseReceiveRoutes from "./purchase-receive.routes";
import billRoutes from "./bill.routes";
import vendorCreditRoutes from "./vendor-credit.routes";
import paymentMadeRoutes from "./payment-made.routes";
import paymentReceivedRoutes from "./payment-received.routes";
import retainerInvoiceRoutes from "./retainer-invoice.routes";
import journalRoutes from "./journal.routes";
import projectRoutes from "./projects";
import currencyAdjustmentRoutes from "./currency-adjustment.routes";
import bulkUpdateRoutes from "./bulk-update.routes";
import documentRoutes from "./document.routes";
import reportRoutes from "./report.routes";
import inventoryRoutes from "./inventory.routes";
import fixedAssetRoutes from "./fixed-asset.routes";
import packageRoutes from "./package.routes";
import moveOrderRoutes from "./move-order.routes";
import putawayRoutes from "./putaway.routes";
import warehouseRoutes from "./warehouse.routes";
import ocrRoutes from "./ocr.routes";
import chatRoutes from "./chat.routes";
import agentRoutes from "./agent.routes";
import transactionLockRoutes from "./transaction-lock.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/organizations", organizationRoutes);
router.use("/roles", roleRoutes);
router.use("/accounts", accountRoutes);
router.use("/contacts", contactRoutes);
router.use("/items", itemRoutes);
router.use("/currencies", currencyRoutes);
router.use("/settings", settingsRoutes);
router.use("/quotes", quoteRoutes);
router.use("/sales-orders", salesOrderRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/credit-notes", creditNoteRoutes);
router.use("/recurring-invoices", recurringInvoiceRoutes);
router.use("/delivery-challans", deliveryChallanRoutes);
router.use("/upload", uploadRoutes);
router.use("/gstin", gstinRoutes);
router.use("/expenses", expenseRoutes);
router.use("/recurring-expenses", recurringExpenseRoutes);
router.use("/recurring-bills", recurringBillRoutes);
router.use("/tds-taxes", tdsTaxRoutes);
router.use("/tcs-taxes", tcsTaxRoutes);
router.use("/purchase-orders", purchaseOrderRoutes);
router.use("/purchase-receives", purchaseReceiveRoutes);
router.use("/bills", billRoutes);
router.use("/vendor-credits", vendorCreditRoutes);
router.use("/payments-made", paymentMadeRoutes);
router.use("/payments-received", paymentReceivedRoutes);
router.use("/retainer-invoices", retainerInvoiceRoutes);
router.use("/journals", journalRoutes);
router.use("/projects", projectRoutes);
router.use("/currency-adjustments", currencyAdjustmentRoutes);
router.use("/bulk-update", bulkUpdateRoutes);
router.use("/documents", documentRoutes);
router.use("/reports", reportRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/fixed-assets", fixedAssetRoutes);
router.use("/packages", packageRoutes);
router.use("/move-orders", moveOrderRoutes);
router.use("/putaways", putawayRoutes);
router.use("/warehouses", warehouseRoutes);
router.use("/ocr", ocrRoutes);
router.use("/chat", chatRoutes);
router.use("/agent", agentRoutes);
router.use("/transaction-locks", transactionLockRoutes);

export default router;
